/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"F:\PersonalProject\BLE-CC2541\BLE_Meeting\CC2640_NEW\blelib\host\host_pxxx.a"
"F:\PersonalProject\BLE-CC2541\BLE_Meeting\CC2640_NEW\blelib\ctrl\cc2640\cc2640_ctrl_pxxx.a"
"F:\PersonalProject\BLE-CC2541\BLE_Meeting\CC2640_NEW\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
